#!/usr/bin/env bash
# sync-opencode.sh: regenerate .opencode/agents/ from .claude/agents/orch-*.md (the single source).
# opencode can't pick a model per dispatch, so the executor is emitted in three tiers.
# Other providers: ORCH_OC_HAIKU=... ORCH_OC_SONNET=... ORCH_OC_OPUS=... bash sync-opencode.sh
# Output follows the opencode V2 agent format. On opencode V1, delete the `permissions` and `steps` fields.
set -u
ROOT=$(cd "$(dirname "$0")/../../../.." && pwd)
SRC="$ROOT/.claude/agents"
DST="$ROOT/.opencode/agents"
HAIKU=${ORCH_OC_HAIKU:-anthropic/claude-haiku-4-5}
SONNET=${ORCH_OC_SONNET:-anthropic/claude-sonnet-5}
OPUS=${ORCH_OC_OPUS:-anthropic/claude-opus-5}

field() { awk -v k="$1" 'NR > 1 && /^---[ \t]*$/ { exit } index($0, k ": ") == 1 { print substr($0, length(k) + 3); exit }' "$2"; }
body() { awk 'n >= 2 { print; next } /^---[ \t]*$/ { n++ }' "$1"; }

deny_common='  - action: subagent
    resource: "*"
    effect: deny
  - action: skill
    resource: "*"
    effect: deny
  - action: question
    resource: "*"
    effect: deny
  - action: webfetch
    resource: "*"
    effect: deny
  - action: websearch
    resource: "*"
    effect: deny'

only_writes() {
  printf '  - action: edit\n    resource: "*"\n    effect: deny\n  - action: edit\n    resource: "*%s*"\n    effect: allow\n' "$1"
}

# emit <source name> <output name> <model> <description> <extra permission rules>
emit() {
  src="$SRC/$1.md"
  [ -f "$src" ] || { echo "sync-opencode: missing $src" >&2; exit 2; }
  steps=$(field maxTurns "$src")
  {
    echo "---"
    echo "# Generated by .claude/skills/orchestrate/scripts/sync-opencode.sh from .claude/agents/$1.md. Edit that file and re-run."
    printf 'description: "%s"\n' "$(printf '%s' "$4" | sed 's/[\\"]/\\&/g')"
    echo "mode: subagent"
    echo "model: $3"
    echo "steps: ${steps:-40}"
    echo "permissions:"
    echo "$deny_common"
    if [ -n "$5" ]; then printf '%s' "$5"; fi
    echo "---"
    body "$src"
  } > "$DST/$2.md"
  echo "wrote .opencode/agents/$2.md ($3)"
}

mkdir -p "$DST"
d_exec=$(field description "$SRC/orch-executor.md")
emit orch-executor orch-executor-lite "$HAIKU" "$d_exec Cheapest tier, for briefs that contain the full code and touch 1 or 2 files." ""
emit orch-executor orch-executor "$SONNET" "$d_exec Standard tier, for implementation from a precise prose brief." ""
emit orch-executor orch-executor-deep "$OPUS" "$d_exec Strongest tier, for cross-file integration, subtle logic, and third attempts." ""
emit orch-scout orch-scout "$HAIKU" "$(field description "$SRC/orch-scout.md")" "$(only_writes .orchestrator/recon/)
"
emit orch-reviewer orch-reviewer "$SONNET" "$(field description "$SRC/orch-reviewer.md")" "$(only_writes .orchestrator/reports/)
"
